<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle( $this->translate('Article Finder'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    
            
</nav>
        
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('Article Finder') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
         
                        <li class="active"><a href="<?php echo $this->url('article') ?>"><?php echo $this->translate('Artykuły') ?></a></li>
                        <!--<li class="active"><a href="<?php// echo $this->url('home') ?>"><?php //echo $this->translate('Kategorie') ?></a></li>    
                        -->
                         <li class="active">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Kategorie<b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li class="menu-item dropdown dropdown-submenu">
                            <a href="<?php echo $this->url('article', array('action'=>'informatics')) ?>" class="dropdown-toggle" >Informatyka</a>
                        </li>
                        <li class="menu-item dropdown dropdown-submenu">
                            <a href="<?php echo $this->url('article', array('action'=>'physics')) ?>" class="dropdown-toggle" d>Fizyka</a>
                        </li>
                        <li class="menu-item dropdown dropdown-submenu">
                            <a href="<?php echo $this->url('article', array('action'=>'math')) ?>" class="dropdown-toggle" >Matematyka</a>
                        </li>
                        <li class="menu-item dropdown dropdown-submenu">
                            <a href="<?php echo $this->url('article', array('action'=>'biology')) ?>" class="dropdown-toggle" >Biologia</a>
                        </li>
                        <li class="menu-item dropdown dropdown-submenu">
                            <a href="<?php echo $this->url('article', array('action'=>'electronics')) ?>" class="dropdown-toggle" >Elektronika</a>
                        </li>
                        <li class="menu-item dropdown dropdown-submenu">
                            <a href="<?php echo $this->url('article', array('action'=>'other')) ?>" class="dropdown-toggle" >Inne</a>
                        </li>
                    </ul>
                </li>
                
                
                        <li class="active"><a href="<?php echo $this->url('article', array('action'=>'add')) ?>"><?php echo $this->translate('Utwórz nowy artykuł') ?></a></li>
                        
               <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Szukana fraza ...">
        </div>
        
         <a href="/article"  role="button" class="btn btn-default">
             
                                        <span class="glyphicon glyphicon-search"> Szukaj</span>
                            </a>
        
      </form>
<!--<li class="active"><a href="<?php //echo $this->url('home') ?>"><?php //echo $this->translate('Wyszukiwanie zaawansowane') ?></a></li>
                        -->
                       <!-- <li class="active"><a href="<?php //echo $this->url('home') ?>"><?php //echo $this->translate('Logowanie') ?></a></li>
                       -->
                        
                  </ul>      
                    
                    <ul class="nav navbar-nav navbar-right">
                        <btn-group>
                            <a href="/user/login"  role="button" class="btn btn-success navbar-btn">
                                        <span class="glyphicon glyphicon-user"> Użytkownik</span>
                            </a>
                            <a href="/article/admin"  role="button" class="btn btn-danger navbar-btn">
                                        <span class="glyphicon glyphicon-wrench"> Administracja</span>
                            </a>
                        </btn-group>
   
                    </ul>
                      
                    
                </div><!--/.nav-collapse -->
            </div>
        </nav>


    
  


        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
               
               <!-- <p>&copy; 2005 - <?php //echo 2015 ?> by Zend Technologies Ltd. <?php //echo $this->translate('All rights reserved.') ?></p>-->
            </footer>
            <script src="http://cookiealert.sruu.pl/CookieAlert-latest.min.js"></script>
<script>CookieAlert.init();</script>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
