 <?php
 

 $title = 'Wszystkie artykuły';
 $this->headTitle($title);
 ?>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><?php echo $this->escapeHtml($title); ?></h3>
  </div>
  <div class="panel-body">
 <!--<h1><?php echo $this->escapeHtml($title); ?></h1>-->
<!-- <p>
     <a href="<?php echo $this->url('article', array('action'=>'add'));?>">Add new album</a>
 </p>-->
<!--<nav>
  <ul class="pagination">
    <li>
      <a href="#" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
    <li><a href="#">1</a></li>
    <li><a href="#">2</a></li>
    <li><a href="#">3</a></li>
    <li><a href="#">4</a></li>
    <li><a href="#">5</a></li>
    <li>
      <a href="#" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
  </ul>
</nav>
-->

 <table class="table">
 <tr>
     
     
     <th>ID artukułu</th>
     <th>Kategoria</th>
     <th>Tytuł</th>
     <th>Data utworzenia/modyfikacji</th>
     <th>Autor</th>
     <th>Opcje</th>
 </tr>
 
 <?php foreach ($articles as $article) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($article->id_artykulu);?></td>
     <td>
      <?php switch ($this->escapeHtml($article->id_kategorii)){
     
 case 1: 
     echo "Informatyka";
     
     break;
 case 2: 
     echo "Fizyka";
    
     break;
  case 3: 
     echo "Matematyka";
      
     break;
 case 4: 
     echo "Biologia";
     break;
  case 5: 
     echo "Elektronika";
     break;
 case 6: 
     echo "Inne";
     break;
 
 }?>
     </td>
     <td><?php echo $this->escapeHtml($article->tytul);?></td>
     
     <td><?php echo $this->escapeHtml($article->data_dodania);?></td>
     <td><?php echo $this->escapeHtml($article->email_autora);?></td>
     <td>
         <a href="<?php echo $this->url('article',
             array('action'=>'edit', 'id_artykulu' => $article->id_artykulu));?>">Edytuj</a>
         <a href="<?php echo $this->url('article',
             array('action'=>'delete', 'id_artykulu' => $article->id_artykulu));?>">Usuń</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>

  </div>
</div>