<?php
namespace Article;
 
 $title = 'Edytuj wybrany artykuł';
 $this->headTitle($title);
 ?>

<!--<script src="../ckeditor/ckeditor.js"></script>-->
<script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
 <script> tinymce.init({
  selector: "#tekst_ckeditor",
  height: 200,
  theme: 'modern',
  plugins: [
    'advlist autolink lists link image charmap print preview hr anchor pagebreak',
    'searchreplace wordcount visualblocks visualchars code fullscreen',
    'insertdatetime media nonbreaking save table contextmenu directionality',
    'emoticons template paste textcolor colorpicker textpattern imagetools'
  ],
  toolbar1: 'insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image',
  toolbar2: 'print preview media | forecolor backcolor emoticons',
  image_advtab: true,
  templates: [
    { title: 'Test template 1', content: 'Test 1' },
    { title: 'Test template 2', content: 'Test 2' }
  ],
  content_css: [
    '//fast.fonts.net/cssapi/e6dc9b99-64fe-4292-ad98-6974f93cd2a2.css',
    '//www.tinymce.com/css/codepen.min.css'
  ]
 });</script>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 
 
                <?php
    /*            
 $form = $this->form;
 $form->setAttribute('action', $this->url(
     'article',
     array(
         'action' => 'edit',
         'id_artykulu'     => $this->id_artykulu,
     )
 ));
 $form->prepare();
 
 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id_artykulu'));
 echo $this->formHidden($form->get('data_dodania'));
 //echo $this->formHidden($form->get('email_autora'));
 echo $this->formRow($form->get('tytul')->setAttribute('class', 'form-control'));
 echo $this->formRow($form->get('id_kategorii')->setAttribute('class', 'form-control'));//->setAttribute('options', $data));
 echo $this->formRow($form->get('tekst')->setAttribute('class', 'form-control'));  
 //echo $this->form()->getMessages();
?> 
        
      <script>
                 if( !('tekst_ckeditor' in CKEDITOR.instances)) {
                        CKEDITOR.replace( 'tekst_ckeditor', {
    toolbar: 'Basic',
    uiColor: '#eee'
});
            </script>

</form>

        </br>
<?php 


echo $this->formSubmit($form->get('submit'));

 echo $this->form()->closeTag();
 */
 //               $form->setAttribute('action', $this->url('article', array('action' => 'add')));
 //$form->prepare();
  $form->setAttribute('action', $this->url(
     'article',
     array(
         'action' => 'edit',
         'id_artykulu'     => $this->id_artykulu,
     )
 ));
 $form->prepare();
 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id_artykulu'));
 echo $this->formHidden($form->get('data_dodania'));
// echo $this->formHidden($form->get('email_autora'));
 echo $this->formRow($form->get('tytul')->setAttribute('class', 'form-control'));
 echo $this->formRow($form->get('id_kategorii')->setAttribute('class', 'form-control'));//->setAttribute('options', $data));
 echo $this->formRow($form->get('tekst')->setAttribute('class', 'form-control')); ?>  

      <!-- <script>
             CKEDITOR.replace( 'tekst_ckeditor' );
        </script>
          </br>-->
<!-- 
<script>
                 if( ('tekst_ckeditor' in CKEDITOR.instances)) {
                        CKEDITOR.replace( 'tekst_ckeditor', {
    toolbar: 'Basic',
    uiColor: '#eee'
});
            </script>-->
<?php echo $this->formSubmit($form->get('submit'));

 echo $this->form()->closeTag();
 
 